apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: takesu-argocd-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/takaesu-junya/test-argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: takaesu-test-argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true # delete the actual cluster when the manifest files are deleted.
